### ISSUE TITLE
RTI DDS LabVIEW communication Issue.

### ISSUE THREAD

**Issue by yunbum** [SynapseProgramming/ros2labview_examples#7]
Hi. I'm robot developer using RTI DDS with LabVIEW.

I do need help for those inter communication.

I followed same sequence and LabVIEW examples. But at the topic name, it shows error 'type mismatch'
Can I get any comment?

I attached the pictures.

p.s below is my github & youtube channel for what I do.
https://github.com/yunbum
https://www.youtube.com/channel/UCd23NgICe3702uqAAk4HYFQ/videos

![RTI DDS setting 2022-05-31 pptx (2)](https://user-images.githubusercontent.com/32663016/171122875-390675b7-22b3-4186-b0b0-0f2f43398900.jpg)
![RTI DDS setting 2022-05-31 pptx (3)](https://user-images.githubusercontent.com/32663016/171122882-f1d585f8-3204-4bed-8048-34133755072e.jpg)
![RTI DDS setting 2022-05-31 pptx (4)](https://user-images.githubusercontent.com/32663016/171122885-4b65d3f0-4e1c-4ea1-8718-5372391bf8d4.jpg)
![RTI DDS setting 2022-05-31 pptx](https://user-images.githubusercontent.com/32663016/171122888-1036209d-d18f-43d9-8f84-c03184e0bf4c.jpg)
![RTI DDS setting 2022-05-31 pptx (1)](https://user-images.githubusercontent.com/32663016/171122890-e09d47ee-6135-4bbe-9ec7-9130e4b59d82.jpg)

**Comment by SynapseProgramming** [comment]
Hi, I have a couple of questions.
1.) Firstly, for the data type input into the create advanced reader vi, is the type of the constant also int 32 ?
2.) Are you able to use the rti dds toolkit to pub/sub between labview vi's on the same pc?

**Comment by yunbum** [comment]
Hi I do appreciae your reply.

Answer for qeustions

1) yes, I followed the your instruction basically.

2) It's no problem, basic rti LabVIEW examples and communicate between LabVIEW vis
>I attached the capture image
![RTI default LabVIEW double example](https://user-images.githubusercontent.com/32663016/171308211-68b0cc63-5b6e-4a44-b79a-a065f55fcff9.JPG)

**Comment by SynapseProgramming** [comment]
Ok. In this case, 

1) Are you able to ping your ros2 pc from your labview pc and vice versa ? 
2) Are you able to pub/sub messages of type std_msgs/int32 between ros2 nodes on your ubuntu machine ? 
3) Have you set the domain ID to be 0 on your ros machine ?

**Comment by yunbum** [comment]
Ok. In this case,

1. Are you able to ping your ros2 pc from your labview pc and vice versa ?
>Yes, basically no problem connected each other rti-console

3. Are you able to pub/sub messages of type std_msgs/int32 between ros2 nodes on your ubuntu machine ?
>yes, but I got some 'transport' sw installation > non-addressable locator error

![Screenshot from 2022-06-06 13-57-22](https://user-images.githubusercontent.com/32663016/172098270-0dfd0a00-59a9-4041-a657-c0c562d92dfd.png)


4. Have you set the domain ID to be 0 on your ros machine ?
>yes.

- I got comment RTI corporate like below
- Did you modyfied the USER_QOS_PROFILES.xml ?
https://www.rti.com/blog/ros2-dds-a-field-guide-to-interoperability

<img width="530" alt="rti USER_QOS_PROFILES xml" src="https://user-images.githubusercontent.com/32663016/172098350-59ad50cf-2475-467e-b853-619c1353dedf.PNG">

**Comment by yunbum** [comment]
It looks like rti dds version issue at this moment.
What is the versin of rti dds that you installed?

**Comment by yunbum** [comment]
I succeed comunicate between ROS2 and LabVIEW with DDS.
It's bashrc configuration problem...

By the way, can you share the bashrc file that you tested?

**Comment by yunbum** [comment]
Hi, I test without error int, string example. But I can not run cluster and other custom type.
Can you give me any comment for this?

**Comment by yunbum** [comment]
Sorry for mass comment. I finally tested without problem in using cluster type..

I will close issue soon. :)
